In [4]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from uncertainties import ufloat
from uncertainties import unumpy as unp

from functions import fit, G, r, rotate_data

In [11]:
np.append(unp.uarray([1, 2, 3], [0.4, 0.5, 0.6]), [ufloat(1, 0.1), ufloat(2, 0.2)])

array([1.0+/-0.4, 2.0+/-0.5, 3.0+/-0.6, 1.0+/-0.1, 2.0+/-0.2],
      dtype=object)

In [3]:
t, x, y = np.loadtxt('measurement2/zero.txt', skiprows=2, unpack=True)
rotate_data(x, y)

(array([1296.39818012, 1295.39700013, 1295.39253841, ..., 1215.37473233,
        1214.37181722, 1213.37732983], shape=(1927,)),
 array([-0.0057834 , -0.0409776 , -0.22092229, ...,  0.0525924 ,
        -0.05258029,  0.18214255], shape=(1927,)),
 None)

In [3]:
#T = ufloat(379.9587037978669, 0) # mean of both, in principle we have zero measurement for full glory
T = fit(*np.loadtxt('measurement2/zero.txt', skiprows=2, unpack=True), cutoff=500, duration=True)
#fit: T0, dtheta1, dtheta2
#theta1=unp.uarray(1042.074833852749, 0 ) #conversion factor for vid setup 1 in cm/'m'. used squared addition here
#theta2=unp.uarray(1249.6597283089984, 0)
theta1 = fit(*np.loadtxt('measurement2/dat_pos1_2.txt', skiprows=2, unpack=True), cutoff=500, angle=True)
theta2 = fit(*np.loadtxt('measurement2/dat_pos2_2.txt', skiprows=2, unpack=True), cutoff=500, angle=True)
conversion_factor = 0.0655

print(G(theta1, theta2, T, conversion_factor))

(1.67+/-0.04)e-10


/home/lucas/anaconda3/lib/python3.12/site-packages/uncertainties/core.py:1024: UserWarning: Using UFloat objects with std_dev==0 may give unexpected results.
  warn("Using UFloat objects with std_dev==0 may give unexpected results.")
